# The Site Configuration
theme: jekyll-theme-chirpy
lang: ko
timezone: Asia/Seoul

title: "Jin-Hyeong's Dev Log"
tagline: "백엔드 개발과 AI를 공부하는 개발자"
description: >-
  학부 졸업을 앞두고 백엔드 프로그래밍, RAG, 서비스개발 과정을 기록하는 공간입니다.

url: "https://jin3402.github.io"
baseurl: ""

github:
  username: jin3402

social:
  name: "이진형"
  email: gng09125@naver.com
  links:
    - https://github.com/jin3402
